on: 
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_call:
    inputs:
      environment:
        type: string
        description: "input user name"
        required: true
        
        
    # secrets:
    #   token:
    #     required: true                             
jobs:
  development:
    runs-on: ubuntu-latest
    if: inputs.environment == 'dev'
    steps:
      - name: run a Hello Script
        run: echo Hello, ${{ env.username }}
        env:
          username: ${{ secrets.username }}
          environment: "dev"
        
        
  production:
    runs-on: ubuntu-latest
    #needs: development
    if: inputs.environment == 'prod'
    steps:
      - name: run a Hello Script
        run: echo Hello, ${{ env.username }}
        env:
          username: ${{ secrets.username }}
          environment: "prod"